export const data = {
  "Lunar Months List": [
    "Chaitra",
    "Vaishakha",
    "Jyeshtha",
    "Ashadha",
    "Shravana",
    "Bhadrapada",
    "Ashwina",
    "Kartika",
    "Margashirsha",
    "Pausha",
    "Magha",
    "Phalguna",
  ],
  "Nakshatra List": [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishtha",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
  ],
  "Yoga Names": [
    "Vishkambha",
    "Priti",
    "Ayushmana",
    "Saubhagya",
    "Shobhana",
    "Atiganda",
    "Sukarma",
    "Dhriti",
    "Shula",
    "Ganda",
    "Vriddhi",
    "Dhruva",
    "Vyaghata",
    "Harshana",
    "Vajra",
    "Siddhi",
    "Vyatipata",
    "Variyana",
    "Parigha",
    "Shiva",
    "Siddha",
    "Sadhya",
    "Shubha",
    "Shukla",
    "Brahma",
    "Indra",
    "Vaidhriti",
  ],
  "Karana Names": [
    "Kinstughna",
    "Bava",
    "Balava",
    "Kaulava",
    "Taitila",
    "Garaja",
    "Vanija",
    "Vishti",
    "Shakuni",
    "Chatushpada",
    "Nagava",
  ],
  "Tithi Names": [
    "Shukla Pratipada",
    "Shukla Dwitiya",
    "Shukla Tritiya",
    "Shukla Chaturthi",
    "Shukla Panchami",
    "Shukla Shashthi",
    "Shukla Saptami",
    "Shukla Ashtami",
    "Shukla Navami",
    "Shukla Dashami",
    "Shukla Ekadashi",
    "Shukla Dwadashi",
    "Shukla Trayodashi",
    "Shukla Chaturdashi",
    "Shukla Purnima",
    "Krishna Pratipada",
    "Krishna Dwitiya",
    "Krishna Tritiya",
    "Krishna Chaturthi",
    "Krishna Panchami",
    "Krishna Shashthi",
    "Krishna Saptami",
    "Krishna Ashtami",
    "Krishna Navami",
    "Krishna Dashami",
    "Krishna Ekadashi",
    "Krishna Dwadashi",
    "Krishna Trayodashi",
    "Krishna Chaturdashi",
    "Krishna Amavasya",
  ],
  "Rashi Names": [
    "Mesha",
    "Vrishabha",
    "Mithuna",
    "Karka",
    "Simha",
    "Kanya",
    "Tula",
    "Vrishchika",
    "Dhanu",
    "Makara",
    "Kumbha",
    "Meena",
  ],
  "Anandadi Yoga Names": [
    "Ananda",
    "Siddhi",
    "Kaladanda",
    "Mrityu",
    "Dhumra",
    "Asukha",
    "Dhata/Prajapati",
    "Saubhagya",
    "Saumya",
    "Bahu Sukha",
    "Dhwanksha",
    "Dhanakshaya",
    "Ketu/Dhwaja",
    "Saubhagya",
    "Shrivatsa",
    "Saukhyasampatti",
    "Vajra",
    "Kshaya",
    "Mudgara",
    "Lakshmikshaya",
    "Chhatra",
    "Rajasanmana",
    "Mitra",
    "Pushti",
    "Manasa",
    "Saubhagya",
    "Padma",
    "Dhanagama",
    "Lumbaka",
    "Dhanakshaya",
    "Utpata",
    "Prananasha",
    "Mrityu",
    "Mrityu",
    "Kana",
    "Klesha",
    "Siddhi",
    "Karyasiddhi",
    "Shubha",
    "Kalyana",
    "Amrita",
    "Rajasanmana",
    "Mushala",
    "Dhanakshaya",
    "Gada",
    "Bhaya",
    "Matanga",
    "Kulavriddhi",
    "Rakshasa",
    "Mahakashta",
    "Chara",
    "Karyasiddhi",
    "Sthira",
    "Griharambha",
    "Vardhamana",
    "Vivaha",
  ],
  "Samvatsara Names": [
    "Prabhava",
    "Vibhava",
    "Shukla",
    "Pramoda",
    "Prajapati",
    "Angira",
    "Shrimukha",
    "Bhava",
    "Yuva",
    "Dhata",
    "Ishwara",
    "Bahudhanya",
    "Pramathi",
    "Vikrama",
    "Vrisha",
    "Chitrabhanu",
    "Subhanu",
    "Tarana",
    "Parthiva",
    "Vyaya",
    "Sarvajit",
    "Sarvadhari",
    "Virodhi",
    "Vikriti",
    "Khara",
    "Nandana",
    "Vijaya",
    "Jaya",
    "Manmatha",
    "Durmukha",
    "Hemalambi",
    "Vilambi",
    "Vikari",
    "Sharvari",
    "Plava",
    "Shubhakrit",
    "Shobhakrit",
    "Krodhi",
    "Vishvavasu",
    "Parabhava",
    "Plavanga",
    "Kilaka",
    "Saumya",
    "Sadharana",
    "Virodhakrit",
    "Paridhavi",
    "Pramadi",
    "Aananda",
    "Rakshasa",
    "Nala",
    "Pingala",
    "Kalayukta",
    "Siddharthi",
    "Raudra",
    "Durmati",
    "Dundubhi",
    "Rudhirodgari",
    "Raktaksha",
    "Krodhana",
    "Kshaya",
  ],
};

export const calender_data = [
  { weekday: "SUN" },
  {
    date: "30/03/2025",
    hindi_num: "16",
    date_num: "30",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sun",
    sunrise: "06:13",
    sunset: "18:38",
    tithi: "Pratipada Shukla",
    moon: "Meena 16:35",
    nakshatra: "Revati 16:35",
  },
  {
    date: "02/03/2025",
    hindi_num: "18",
    date_num: "02",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sun",
    sunrise: "06:45",
    sunset: "18:22",
    tithi: "Tritiya Shukla",
    moon: "Meena 30:39+",
    nakshatra: "U Bhadrapada 08:59",
  },
  {
    date: "09/03/2025",
    hindi_num: "25",
    date_num: "09",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sun",
    sunrise: "06:38",
    sunset: "18:26",
    tithi: "Dashami Shukla",
    moon: "Mithuna 17:45",
    nakshatra: "Punarvasu 23:55",
  },
  {
    date: "16/03/2025",
    hindi_num: "2",
    date_num: "16",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sun",
    sunrise: "06:30",
    sunset: "18:30",
    tithi: "Dwitiya Krishna",
    moon: "Kanya 25:15+",
    nakshatra: "Hasta 11:45",
  },
  {
    date: "23/03/2025",
    hindi_num: "9",
    date_num: "23",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sun",
    sunrise: "06:22",
    sunset: "18:34",
    tithi: "Navami Krishna",
    moon: "Dhanu",
    nakshatra: "P Ashadha 28:18+",
  },

  { weekday: "MON" },
  {
    date: "31/03/2025",
    hindi_num: "17",
    date_num: "31",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Mon",
    sunrise: "06:12",
    sunset: "18:38",
    tithi: "Dwitiya Shukla",
    moon: "Mesha",
    nakshatra: "Ashwini 13:45",
  },
  {
    date: "03/03/2025",
    hindi_num: "19",
    date_num: "03",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Mon",
    sunrise: "06:44",
    sunset: "18:22",
    tithi: "Chaturthi Shukla",
    moon: "Mesha",
    nakshatra: "Ashwini 28:29+",
  },
  {
    date: "10/03/2025",
    hindi_num: "26",
    date_num: "10",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Mon",
    sunrise: "06:36",
    sunset: "18:27",
    tithi: "Ekadashi Shukla",
    moon: "Karka",
    nakshatra: "Pushya 24:51+",
  },
  {
    date: "17/03/2025",
    hindi_num: "3",
    date_num: "17",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Mon",
    sunrise: "06:28",
    sunset: "18:31",
    tithi: "Tritiya Krishna",
    moon: "Tula",
    nakshatra: "Chitra 14:47",
  },
  {
    date: "24/03/2025",
    hindi_num: "10",
    date_num: "24",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Mon",
    sunrise: "06:20",
    sunset: "18:35",
    tithi: "Dashami Krishna",
    moon: "Dhanu 10:25",
    nakshatra: "U Ashadha 28:27+",
  },

  { weekday: "TUE" },
  {
    date: "25/02/2025",
    hindi_num: "12",
    date_num: "25",
    date_month_num: "02",
    date_year_num: "2025",
    weekday: "Tue",
    sunrise: "06:50",
    sunset: "18:18",
    tithi: "Dwadashi Krishna",
    moon: "Makara",
    nakshatra: "U Ashadha 18:31",
  },
  {
    date: "04/03/2025",
    hindi_num: "20",
    date_num: "04",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Tue",
    sunrise: "06:43",
    sunset: "18:23",
    tithi: "Panchami Shukla",
    moon: "Mesha",
    nakshatra: "Bharani 26:37+",
  },
  {
    date: "11/03/2025",
    hindi_num: "27",
    date_num: "11",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Tue",
    sunrise: "06:35",
    sunset: "18:27",
    tithi: "Dwadashi Shukla",
    moon: "Karka 26:15+",
    nakshatra: "Ashlesha 26:15+",
  },
  {
    date: "18/03/2025",
    hindi_num: "4",
    date_num: "18",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Tue",
    sunrise: "06:27",
    sunset: "18:31",
    tithi: "Chaturthi Krishna",
    moon: "Tula",
    nakshatra: "Swati 17:52",
  },
  {
    date: "25/03/2025",
    hindi_num: "11",
    date_num: "25",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Tue",
    sunrise: "06:19",
    sunset: "18:35",
    tithi: "Ekadashi Krishna",
    moon: "Makara",
    nakshatra: "Shravana 27:49+",
  },
  { weekday: "WED" },
  {
    date: "26/02/2025",
    hindi_num: "13",
    date_num: "26",
    date_month_num: "02",
    date_year_num: "2025",
    weekday: "Wed",
    sunrise: "06:49",
    sunset: "18:19",
    tithi: "Trayodashi Krishna",
    moon: "Makara 28:37+",
    nakshatra: "Shravana 17:23",
  },
  {
    date: "05/03/2025",
    hindi_num: "21",
    date_num: "05",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Wed",
    sunrise: "06:42",
    sunset: "18:23",
    tithi: "Shashthi Shukla",
    moon: "Mesha 08:13",
    nakshatra: "Krittika 25:08+",
  },
  {
    date: "12/03/2025",
    hindi_num: "28",
    date_num: "12",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Wed",
    sunrise: "06:34",
    sunset: "18:28",
    tithi: "Trayodashi Shukla",
    moon: "Simha",
    nakshatra: "Magha 28:05+",
  },
  {
    date: "19/03/2025",
    hindi_num: "5",
    date_num: "19",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Wed",
    sunrise: "06:26",
    sunset: "18:32",
    tithi: "Panchami Krishna",
    moon: "Tula 14:07",
    nakshatra: "Vishakha 20:50",
  },
  {
    date: "26/03/2025",
    hindi_num: "12",
    date_num: "26",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Wed",
    sunrise: "06:18",
    sunset: "18:36",
    tithi: "Dwadashi Krishna",
    moon: "Makara 15:14",
    nakshatra: "Dhanishtha 26:30+",
  },
  { weekday: "THU" },
  {
    date: "27/02/2025",
    hindi_num: "14",
    date_num: "27",
    date_month_num: "02",
    date_year_num: "2025",
    weekday: "Thu",
    sunrise: "06:48",
    sunset: "18:20",
    tithi: "Chaturdashi Krishna",
    moon: "Kumbha",
    nakshatra: "Dhanishtha 15:43",
  },
  {
    date: "06/03/2025",
    hindi_num: "22",
    date_num: "06",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Thu",
    sunrise: "06:41",
    sunset: "18:24",
    tithi: "Saptami Shukla",
    moon: "Vrishabha",
    nakshatra: "Rohini 24:05+",
  },
  {
    date: "13/03/2025",
    hindi_num: "29",
    date_num: "13",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Thu",
    sunrise: "06:33",
    sunset: "18:28",
    tithi: "Chaturdashi Shukla",
    moon: "Simha",
    nakshatra: "P Phalguni 30:19+",
  },
  {
    date: "20/03/2025",
    hindi_num: "6",
    date_num: "20",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Thu",
    sunrise: "06:25",
    sunset: "18:32",
    tithi: "Shashthi Krishna",
    moon: "Vrishchika",
    nakshatra: "Anuradha 23:31",
  },
  {
    date: "27/03/2025",
    hindi_num: "13",
    date_num: "27",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Thu",
    sunrise: "06:17",
    sunset: "18:36",
    tithi: "Trayodashi Krishna",
    moon: "Kumbha",
    nakshatra: "Shatabhisha 24:34+",
  },
  { weekday: "FRI" },
  {
    date: "28/02/2025",
    hindi_num: "15",
    date_num: "28",
    date_month_num: "02",
    date_year_num: "2025",
    weekday: "Fri",
    sunrise: "06:47",
    sunset: "18:20",
    tithi: "Pratipada Shukla",
    moon: "Kumbha 29:58+",
    nakshatra: "Shatabhisha 13:40",
  },
  {
    date: "07/03/2025",
    hindi_num: "23",
    date_num: "07",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Fri",
    sunrise: "06:40",
    sunset: "18:25",
    tithi: "Ashtami Shukla",
    moon: "Vrishabha 11:45",
    nakshatra: "Mrigashira 23:32",
  },
  {
    date: "14/03/2025",
    hindi_num: "30",
    date_num: "14",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Fri",
    sunrise: "06:32",
    sunset: "18:29",
    tithi: "Purnima Shukla",
    moon: "Simha 12:56",
    nakshatra: "U Phalguni",
  },
  {
    date: "21/03/2025",
    hindi_num: "7",
    date_num: "21",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Fri",
    sunrise: "06:24",
    sunset: "18:33",
    tithi: "Saptami Krishna",
    moon: "Vrishchika 25:46+",
    nakshatra: "Jyeshtha 25:46+",
  },
  {
    date: "28/03/2025",
    hindi_num: "14",
    date_num: "28",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Fri",
    sunrise: "06:16",
    sunset: "18:37",
    tithi: "Chaturdashi Krishna",
    moon: "Kumbha 16:48",
    nakshatra: "P Bhadrapada 22:09",
  },
  { weekday: "SAT" },
  {
    date: "01/03/2025",
    hindi_num: "17",
    date_num: "01",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sat",
    sunrise: "06:46",
    sunset: "18:21",
    tithi: "Dwitiya Shukla",
    moon: "Meena",
    nakshatra: "P Bhadrapada 11:22",
  },
  {
    date: "08/03/2025",
    hindi_num: "24",
    date_num: "08",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sat",
    sunrise: "06:39",
    sunset: "18:25",
    tithi: "Navami Shukla",
    moon: "Mithuna",
    nakshatra: "Ardra 23:28",
  },
  {
    date: "15/03/2025",
    hindi_num: "1",
    date_num: "15",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sat",
    sunrise: "06:31",
    sunset: "18:29",
    tithi: "Pratipada Krishna",
    moon: "Kanya",
    nakshatra: "U Phalguni 08:54",
  },
  {
    date: "22/03/2025",
    hindi_num: "8",
    date_num: "22",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sat",
    sunrise: "06:23",
    sunset: "18:33",
    tithi: "Ashtami Krishna",
    moon: "Dhanu",
    nakshatra: "Mula 27:23+",
  },
  {
    date: "29/03/2025",
    hindi_num: "15",
    date_num: "29",
    date_month_num: "03",
    date_year_num: "2025",
    weekday: "Sat",
    sunrise: "06:15",
    sunset: "18:37",
    tithi: "Amavasya Krishna",
    moon: "Meena",
    nakshatra: "U Bhadrapada 19:26",
  },
];

export const panchangData = [
  { label: "Sunrise", value: "06:30 AM" },
  { label: "Sunset", value: "06:30 PM" },
  { label: "Moonrise", value: "08:24 PM" },
  { label: "Moonset", value: "07:23 AM" },
  { label: "Shaka Samvat", value: "1946 Krodhi" },
  { label: "Vikram Samvat", value: "2081 Pingala" },
  { label: "Gujarati Samvat", value: "2081 Nala" },
  { label: "Amanta Month", value: "Phalguna" },
  { label: "Purnimanta Month", value: "Chaitra" },
  { label: "Weekday", value: "Raviwara" },
  { label: "Paksha", value: "Krishna Paksha" },
  { label: "Tithi", value: "Dwitiya upto 04:58 PM" },
  { label: "Nakshatra", value: "Hasta upto 11:45 AM" },
  { label: "Yoga", value: "Vriddhi upto 02:49 PM" },
  { label: "Karana", value: "Garaja upto 04:58 PM" },
  { label: "Karana", value: "Vanija upto 06:14 AM, Mar 17" },
  { label: "Pravishte/Gate", value: "3" },
  { label: "Sunsign", value: "Meena" },
  { label: "Moonsign", value: "Kanya upto 01:15 AM, Mar 17" },
  { label: "Rahu Kalam", value: "05:00 PM to 06:30 PM" },
  { label: "Guilkai Kalam", value: "03:30 PM to 05:00 PM" },
  { label: "Yamaganda", value: "12:30 PM to 02:00 PM" },
  { label: "Abhijit", value: "12:06 PM to 12:54 PM" },
  { label: "Dur Muhurtam", value: "04:54 PM to 05:42 PM" },
];

export const footerData = [
  {
    title: "Astronomy",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Solar Eclipse",
      "Lunar Eclipse",
      "Vernal Equinox",
      "Summer Solstice",
      "Autumnal Equinox",
      "Winter Solstice",
    ],
  },
  {
    title: "Astrology",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Full Moon Dates",
      "New Moon Dates",
      "Planetary Positions",
      "Graha Aeta & Uday",
      "Graha Vakri & Nargi",
      "Graha Gochara",
    ],
  },
  {
    title: "Nurtward",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Marriage Dates",
      "Griha Pravesh",
      "Buying Car",
      "Property Purchase",
    ],
  },
  {
    title: "Panchang",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Panchak",
      "Ganda Noola",
      "Bhadra Vichar",
      "Rahu Kalam",
      "Nakshatra",
      "Abhijit Nakshatra",
    ],
  },
  {
    title: "Amirisiddhi Yoga",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Sarvarthasiddhi Yoga",
      "Amirisiddhi Yoga",
      "Dwipushkar Yoga",
      "Tripushkar Yoga",
      "Ravi Pushya",
      "Guru Pushya",
      "Ravi Yoga",
    ],
  },
  {
    title: "Tamil Panchangan",
    icon: "https://www.drikpanchang.com/images/footer/2x/xanchor_kalash.png.pagespeed.ic.UMEHr3PHbU.webp",
    items: [
      "Tamil Panchangan",
      "Gowri Nalla Neram",
      "Tamil Calendar",
      "Karthigai Days",
      "Kanda Sashti Days",
    ],
  }
];
